### ISSUE TITLE
Using Minimum and Maximum date

### ISSUE THREAD

**Issue by jmelendev** [AppAndFlow/react-native-quickpicker#1]
Hey there,

This may be a question more than an issue but how could i prevent the date picker from picking a date in the past and prevent the date from being more than 24 hours from now?

**Comment by Valiums** [comment]
Hi @jmelendev!

I guess you could do:
```

const minimumDate = new Date();
and then
const maximumDate = new Date();
maximumDate.setDate(maximumDate.getDate() + 1);

then on the picker config you set 
minimumDate={minimumDate}
maximumDate={maximumDate}

```

I think that should do it :)
