### ISSUE TITLE
Modal auto-collapses Android

### ISSUE THREAD

**Issue by yasso1am** [AppAndFlow/react-native-quickpicker#5]
quickpicker: 1.2.0
react-native - 31.0.1 (from expo)
expo sdk: 31.0.4

On iOS, the picker behaves as expected, opening to display my items.
![iosbehavior](https://user-images.githubusercontent.com/39067243/51196255-9892bc80-18a3-11e9-8279-3ceea931a217.gif)

On Android, the picker briefly opens into the modal and then items disappear and modal collapses, becoming unusable.
![androidbehavior](https://user-images.githubusercontent.com/39067243/51196276-a1838e00-18a3-11e9-8bfe-95dc95fdba96.gif)

Code that calls the picker
 ```
 pickWorkoutType = () => {
    this.editActive('workoutType')
    const { workout } = this.props
    if (workout.goal){
      return
    } else {
        const activities = ['Running', 'Biking', 'Rowing', 'Walking']
          QuickPicker.open({
            pickerType:"normal",
            items: activities,
            selectedValue: this.state.workoutType,
            onValueChange: (workoutType) => this.setState({ workoutType }),
            doneButtonTextStyle: { color: AppStyles.primaryColor},
            onTapOut: QuickPicker.close(),
            topRow: <QuickpickerHeader pickDate={this.pickDate} distance={this.distance} kind={"workout"} text="Select a Workout" />
          })
      }
  }

```

I also attempted setting `androidModalStyle: {height: 250}`, which will keep the modal at a fixed height, however, the items still disappear once the modal opens.

![fixed height android modal](https://user-images.githubusercontent.com/39067243/51196552-338b9680-18a4-11e9-8d4f-0310fe1ed164.png)

The `<QuickPicker />` is located at the root of the project, as the lowest most component (inside the main `<SafeAreaView>`

Not sure where to start trouble shooting this one. I commented out "topRow" seeing as it is no longer respected Android, thinking it might be causing a bug, however that did not help.

**Comment by yasso1am** [comment]
I believe I may have solved my own problem. It appears that on iOS, when the config file includes: `onTapOut: QuickPicker.close()` everything operates as expected.

Unfortunately, with Android, it doesn't work the same. When I pass it `onTapOut: () => QuickPicker.close()` it now performs as expected.

Not sure how to submit a pull request to handle this on Android, but happy to offer that up if desired.

**Comment by Valiums** [comment]
hey @yasso1am, sorry about that, yea the doc is a bit out of date and the lib just doesn't work the same way anymore on Android. Indeed for the moment, the correct work around is to perform some platform check and to use manually QuickPicker.close() when needed.

**Comment by yasso1am** [comment]
That could be one workaround, but the workaround I used has the QuickPicker operating as expected now. Passing it a function equal to QuickPicker.close() solved it.

Thanks for your component.
